volumes:
  postgres-data:

services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=nouns_terminal
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nouns_terminal:
    image: ghcr.io/nouns-terminal/nouns-terminal:latest
    restart: unless-stopped
    environment:
      - PROVIDER_URL
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/nouns_terminal
    depends_on:
      - postgres
    ports:
      - 3003:3003
